apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - chart: jellyfin
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 2.3.0
      helm:
        values: |
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-desec
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
            hosts: 
              - host: jellyfin.bigli.io
                paths:
                  - path: "/"
                    pathType: "ImplementationSpecific"
            tls:
            - secretName: ingress-cert
              hosts:
              - jellyfin.bigli.io
          securityContext:
            runAsUser: 1001
            fsGroup: 1001
          metrics:
            enabled: false
            serviceMonitor:
              enabled: true
          persistence:
            media:
              existingClaim: jellyfin-media
          
    - path: apps/jellyfin
      repoURL: https://github.com/TheBigLee/gitops-k3s.git
      targetRevision: HEAD
  destination:
    namespace: jellyfin
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
