apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - chart: nextcloud
      repoURL: https://nextcloud.github.io/helm/
      targetRevision: 6.6.9
      helm:
        values: |
          image:
            tag: 30.0.8-apache
          nextcloud:
            host: nextcloud.bigli.io
            configs:
              bigli-nextcloud.config.php: |
                 <?php
                    $CONFIG = array (
                    'trusted_proxies' => ['10.43.0.0/16'],
                    'maintenance_window_start' => 1,
                  );
            existingSecret:
              enabled: true
              secretName: nextcloud-creds
              usernameKey: username
              passwordKey: password
            objectStore:
              s3:
                region: nbg1
                enabled: true
                existingSecret: s3-creds
                secretKeys:
                  host: host
                  accessKey: accessKey
                  secretKey: secretKey
                  bucket: bucket
                  sse_c_key: sse_c_key
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-desec
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd,nextcloud-nextcloud-redirectregex@kubernetescrd,nextcloud-nextcloud-headers@kubernetescrd
            tls:
            - secretName: ingress-cert
              hosts:
              - nextcloud.bigli.io
          internalDatabase:
            enabled: false
          postgresql:
            global:
              postgresql:
                auth:
                 existingSecret: psql-creds
                 secretKeys:
                   adminPasswordKey: adminPassword
                   userPasswordKey: db-password
                   replicationPasswordKey: replicationKey
            enabled: true
            primary:
              resources:
                limits:
                  memory: 1Gi
              persistence:
                enabled: true
                storageClass: local-path
          redis:
            enabled: true
            auth:
              existingSecret: redis-creds
              existingSecretPasswordKey: redisPassword
          cronjob:
            enabled: true
          externalDatabase:
            type: postgresql
            existingSecret:
              enabled: true
              secretName: psql-creds
          persistence:
            enabled: true
          startupProbe:
            enabled: true
    - path: apps/nextcloud
      repoURL: https://github.com/TheBigLee/gitops-k3s.git
      targetRevision: HEAD
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
