apiVersion: v1
kind: Secret
metadata:
    name: docspell
    namespace: docspell
type: Opaque
stringData:
    ADMIN_ENDPOINT_SECRET: ENC[AES256_GCM,data:d/RdJGYTwrXhpjdOXQCCm2azGcGFPmo2G655n8fVLho=,iv:F6IXya/KSpd5keIH2RS38RzgxemQUrtYsquebXWV9lE=,tag:TYT1cSpNGYv/cP4u3tAcqg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:smQe2GrZwu8=,iv:KI4NPv1MiDVcF1miBHGpa87hkcAUiv32eVNzGqAv4DQ=,tag:Y56icuQ078DO+9i6nsprCw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:DLSIQbk0VQNQQ+eVVNL2yERUqQ/5n3Vk0eHUJRKASrs=,iv:tyCmFtCvv0PtcJjudmiYwIi3F66Sz3kJVN9JGypgg3Y=,tag:wEUVFStpLiRtxiOYoOibWA==,type:str]
    DB_USER: ENC[AES256_GCM,data:3JIIBfIwrmI=,iv:1QyAOCZfMNZ/z2P7HSbOJsVO6GSD/Ru3fdO5uO6b8Bk=,tag:hDvRNlcIaeOul4wZbsTrLQ==,type:str]
    DOCSPELL_HEADER_VALUE: ENC[AES256_GCM,data:YzXOX4E1YfRFlCBm6u1jsIMqGiUf2oJPu0/q7KzOnrpc9rGtHUmY3leHwjpUtcImVuwi1V00ryYXNUIXhKOkSQ==,iv:rddKok1J2TLf1DZm2N/1A7++TCYQKlUu4H1CLTViO7Y=,tag:WNCafZ9gce8Z6uZ3qeCdIA==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNjdQYmt4MEF4aUpxNUdF
            ZFJnSFBiTkEwWHF0eDFETTdaWlE4YVB1UnpZCnRJVlgvTFVjTi9vMXE0d1pEc2VF
            eSs0MzliRVE1QnJLOTVRVlpCMzJQQ3MKLS0tIFhoeXdPSzZnSzNPb05vTkQwRXBn
            YlRON1Y3T2NubVBMd1piSnR6blRTWkEKWs2fp1uKiFfx4FNHW7AZKmwV0Ddm2RLx
            wZaZ7aM2HlUx8DrZ64FjZcLL3+PswKd3Bl/SiDjz4CWGnc+sWNjgtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUnJ2S040L0hpdWJMdkNv
            S2ptKzM3ZW5iYlVFalRiK2ZIOENra1FIUDMwClNpMkVYRHc4Nk1RQkRhVHAyVU5w
            Q2JKTGNQNFpoUlZjMFdidHg3U09BY2MKLS0tIFNyTDlNdWtWVC9kYUtxWVU1Qjh3
            a3NudFdHWFFKeGhLMWxUZ2pXZ1gzd3cKvlEx5wMUTD1L9mk9QIuDda/qrs77QM8u
            oPs7Ji36rKEUXMh4UPA6j0wshjuCJ6InsJeMi1Gank8wh2+yBnyD2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZGdvSTVLV1pGVjFTUUdk
            MFpFcjlTZUZYR0tXSlhESmkwR1R6WHUvZVFRCjRZZ3dwcXI1a0JkVVEwSmx0dGtW
            SW5tY09BMUMxQ1IzdW4rSlQ4VXVnMk0KLS0tIE9ZVDJKV3YxL1F3Nnk4bGFVdTlK
            UE56SmxaMzc3NFJ3bE4yNWx5dnVldkkKQYt2KuVR3xYV11PCOweSRGqqnYYWjcxp
            RMqGK8UOBDmNR2svHH2ZDR8PAoukvhatEuETGk1/HAI+qMjkzO3FPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T14:33:40Z"
    mac: ENC[AES256_GCM,data:6Mv67GKmcm4Np5j4DQ7RIQVplfUDjd0uQQz4CNPh2hjOCKRHqO2GHXmVwhb7KdlHRGnfnev4lbux35o5TcEoBT+Vr6fvOC/ZOQXy+ParVXNvq80sfgPaAN5mrc0FDXKpJxhsQiTtxAvaHYL1vJM1/6FHvGtYa1uCJYxaFk+SlcA=,iv:mi/1KD/ZrFO4DVkBWlh6bVxzFzLBTfFpMk4UgbTf2rM=,tag:gHewcfElJ0cicO+ssjgXlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
