apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-prometheus'
    spec:
      project: system
      source:
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 70.4.1
        helm:
          values: |
            grafana:
              ingress:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod-desec
                  traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
                hosts:
                  - monitoring.bigli.io
                tls:
                  - secretName: grafana-ingress-cert
                    hosts:
                    - monitoring.bigli.io
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
