apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-local-kube-system
  namespace: argocd
spec:
  project: system
  source:
    path: 'apps/k3s/_system/kube-system'
    repoURL: https://github.com/TheBigLee/gitops-k3s.git
    targetRevision: HEAD
  destination:
    name: k3s
    namespace: kube-system
