apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-prometheus'
    spec:
      project: system
      sources:
        - chart: kube-prometheus-stack
          repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision: 70.4.1
          helm:
            values: |
              grafana:
                persistence:
                  enabled: true
                ingress:
                  enabled: true
                  annotations:
                    cert-manager.io/cluster-issuer: letsencrypt-prod-desec
                    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
                  hosts:
                    - monitoring.bigli.io
                  tls:
                    - secretName: grafana-ingress-cert
                      hosts:
                      - monitoring.bigli.io
              prometheus:
                prometheusSpec:
                  serviceMonitorSelectorNilUsesHelmValues: false
                  retention: 2w
                  retentionSize: 20G  
                  storageSpec:
                  volumeClaimTemplate:
                    spec:
                      storageClassName: local-path
                      resources:
                        requests:
                          storage: 40Gi

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        automated:
          prune: true
