apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.2.5
  destination:
    namespace: kube-system
    name: k3s
  project: system
  syncPolicy:
    automated:
      prune: true
