apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  source:
    path: apps/k3s/_system/system-upgrade-controller
    repoURL: https://github.com/TheBigLee/gitops-k3s.git
    targetRevision: HEAD
  destination:
    namespace: system-upgrade
    name: k3s
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
