apiVersion: v1
kind: Secret
metadata:
    name: backup-bucket-credentials
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:05rapuZn9i6E7a1KN5rxxqqKuKiLzyBv3w==,iv:GA+GWbHJ1FFN/CSQU8PzcC6sLWDZat0BA/R1fGqLt+8=,tag:JLiCdhSRzlMfWs/RZgXlrw==,type:str]
    access-key-secret: ENC[AES256_GCM,data:tBi2Xhu7CynkEGdOlyYla2icm5/SfqXaxf4PJuBQOg==,iv:mSENoKVolbarjE/GZPLk4ji0bP4PnTwfaCCRj/8QUAg=,tag:C43Lp88okh4yqxY2rsVl3w==,type:str]
    password: ENC[AES256_GCM,data:FZDMkpCLkHyKZ6Cwu2eZqdbuJnzIvNpbm2VjHGimbgk=,iv:zVGrr7LpcS9DlTNBx6Nc4B2up5uUNzw0L7LE4Cf3lsw=,tag:Vb4bXwMbwk3dhRP5WfhpwA==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK2Q0bkZxMDlTN3djSmtE
            TDg3RVZsUXhRVGJ4TEtSU2pPbTl2RWU2MnpNCnh0OTNMdFROSmZHOGU3K2RlanVz
            eTZuRzJlRGlzWElwa2Z4bytQR3NTWVUKLS0tIGxPSnpjWVd4ZmNtSVlIaHcxRGtW
            VzdDOC8wWkdFdFBkazkvYUVVZ0gveDAKcQZ0ruKANe0e/An+cKACNxcZdC5kFnMd
            F3eYVwCwXyDgw4n8NIf8uJbj1ksf3ElajzXWwBkLC5phZvnmPSr9iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T19:02:36Z"
    mac: ENC[AES256_GCM,data:iXUD7qVtceVHY1B0a5ypNuGFJorYg8m5D5zen6P8IBsKMsMSnSL4CrQEL2PIFVmtyWCO9cOKnnovAqmyRnU7th6O8TQ5F7lcA5Vk/R3AnjyleatrKi1nC8QHyZlsyvYnqbWx0N9Nm0krP+fiGaGsGclVR0V/CTe8c6DbTZPf+Bw=,iv:Thpo3q7/ZAh1CF1qHzyzZf0vsft78XS4ymlEDtU38PA=,tag:5QoNZTqxJc2JntHDl5GJnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
