apiVersion: v1
kind: Secret
metadata:
    name: s3-creds
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:ut/0bfZhHJ6kENh8LmohR7puNaWCJTy9cB8b,iv:lCgR0gsG4Yw8SxJFAMupb/FdNcxKwZRVB2diAsI4wkc=,tag:/bGnQZzg7ExinuEBBzMEeA==,type:str]
    accessKey: ENC[AES256_GCM,data:DS/XvOyCFQAXhrj6tElEfUZuWOw=,iv:O6OZvKA5c1rCUn94pnRBsISfLhaebellzfue912hvls=,tag:nnr/QBw4Pz+tBr33nsjWQw==,type:str]
    secretKey: ENC[AES256_GCM,data:6e+wtJDe24nRwcC5iDABuKKBNR4rBl8ww3eOaK8XIWMbBUcHbU8DZA==,iv:hypKoOqSxdn7GZWbIIQFnOdH0NlZfzZVgWiWX0ZNBMc=,tag:mpjyucRFmK6rsJoWfEZjtw==,type:str]
    bucket: ENC[AES256_GCM,data:Yz5rsfreXpeal8Vh/T+S,iv:B3RqqxzwrACE+8JiXugeemTNE9QAhjNxfbEoPMbWRO0=,tag:M5NU4m3G+14YX0txL+jLYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENmw2djlwRVFJSnlMUGVF
            K0xsVkRUd0h6QXN6ZVY1VTVwNW1LMTh3N1VBCjY5MGI4Nk5oWG0raGJFM2ROay93
            YXk4VE9WS2dSeTZpRHRYQ0RBVTlDWFEKLS0tIFpRM1pyNWV4dnJDVDFEY1U3Vkhy
            aHpIVmZ0TngrNVRDTStvRnNhUjZPSkUK8Ku6zvTb72AU98k4qoXh+uVcvyYGddbI
            GYJIyHwWaEUCjTkYjS4vO/IsXpCZmB5YFXwTiL7a+ubIKiM3m0lbAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-01T20:14:00Z"
    mac: ENC[AES256_GCM,data:Ae7sIIxR/BiT9BR+a2Vjs8MR9P2I9fTYvDf396s0kMNFdYbcYuI6yYv/i01EBp6Wo0w06Bfs69OvcUlKU2q8OOPSedu8FnsfcUAiIaM6ovhxaxINRx6wU00qBQlAb5DO1e/zkgHxmAlH5c8DZ78aA/e+tceNM13C3J4yRYroN0w=,iv:nuSYFiON42gisp+CsgtjDtlHVI8eaKg0xjiUQJeHvqE=,tag:XmB+vWrLd7ARwme0rxxSUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
