apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - backup-credentials-secret.sops.yaml
  - nextcloud-creds.sops.yaml
  - psql-creds.sops.yaml
  - redis-creds.sops.yaml
