apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-system
  namespace: argocd
spec:
  project: system
  source:
    path: 'apps/raspi5/_system/kube-system'
    repoURL: https://github.com/TheBigLee/gitops-k3s.git
    targetRevision: HEAD
  destination:
    name: raspi5
    namespace: kube-system
