apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-creds
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pUlSY4Y=,iv:g7+I24qZ4KAKIzLbPncVP+UPXQLBQaHjCi8Vf1oDdvE=,tag:ei+L9O0yXjG/LCg/ponMSw==,type:str]
    password: ENC[AES256_GCM,data:CxVOQ+fx1Kn8d5nrS3bK+qxaWYZDxIvuVJ/nVBGZAlE=,iv:Z7bwADwSbz/sWfUpBrjUHsqGQ7AFLOE1uUyqea3ovok=,tag:dn8Gg+W9NJz/Q1m8bHnGYA==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWmRJZjA1RzF3QkZUY01p
            Q0E0N0lWN3pTVU5EekNXM3FtV2xTekJyNEZzCkhPSUdUOEl1RWNjUE5kd2tvUzRB
            cFhzMXJVcjJwWGV3TnVoQ0tXWURUWDgKLS0tIFZSSDJQM2pTekNOb05qeFZJbCtT
            L05ORllpVGErQVpSSWYrc1FrMzVOWG8KOh8Rkvae1VmkbWuudEoRZVEpFs5aiz+Z
            4axBB4GfnS2rNjFOtGn0ksEbJleTBjB1AoiIsJ/7I607XtCUH/sP3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRmloVVZtaWU3RTdDUVp1
            eHZGSjFlcGpQYWphTFRkMzkrZ2IyWUpzeVNZCk5OcTBPa3NJejhXejNSaVNOK0Fo
            eHRvYmppMEJFa1pUci9namxDcTNGRWMKLS0tIHVGV2ZrMFdiYkVZZXZoYXIzaW1X
            TlprdXRnOTZ4aFpLa0RqaHRjWXdHbFUK2/dcNAb2G7r6hM1zcSboN++vjU3F4rm1
            vTi160tm7S4C+Y9WJ+I+jVo26jzapHKUt/mZOoX4Ao9B1q0TQ4A40w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRzlpbEdSdVJ6Ly9YUmI5
            L2lwM2FmWktIdlBXRHlMd05wbmJSbVRxOHhZCjc1bTdTcVR0QTcvOSs5SWlrWkEy
            T0c5d1RYSitacjdYcFE0N3owOWxCemMKLS0tIHVOaUQ0Z0h2aEhhbERtU0hVUllC
            L1BYTjJ2OEZ5NW9adFhNTWZRTUVERVUKWGIuAs3AglgVlVJ1IQ44eOh+58LMSG6P
            QUbFd1sdEvAu4Upb6SkPYNW5wmUZpodAPwelqcX8Ee5/ZdswJ2uc5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16wwrxv5stw6wtsst4sk6yyszj3meggler0awv4d2rs7krjg3jfyqzyj47v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VjAvK01UcEFwa1NiZkdh
            djRCVXVhZTFid0tZSDI0QVUyWTZ0THZybno4CkFrTSt5UHNscjlRbEdPQTU5Smdz
            em9ncUkwaFUzV0MxMTFUa3UzbmRsMEUKLS0tIG1uV01WU2JqSEc2TFNld1U2aTNX
            N0YvN2tXMjF3eldXeU0xZ3dsWnJFSDgKW5WFefLAcZAXMFUZGL3Am76PLHKUYTev
            cfwaGMh6E6UOxk9sX+pvBkG/3OfmSonjVs+MR86ZgqdWZNnNWsEuMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-01T19:42:38Z"
    mac: ENC[AES256_GCM,data:7K39Dn+BQhdUp4BaPl9LgxjyXKUHV5rsdPneeXlxu92votc7oxbVPAJ6eEabk6D+4YNIvvNg/46xYjJNcgsSsxym6nVvKTIcrxIK7q9bypL7SLE5ALf38wwpc2duvNIaEtDFj9pa+Ntr0KXvDlonjkBr+yMadt5ddZangJerJvA=,iv:eax/taQ31Ejn7OH21wSW4sJdNQG/iqWmLQfnbutZM/o=,tag:aQVBA2cBGRXibae5eMX2oQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
