apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-headers
  namespace: nextcloud
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    #Instructs some browsers to not sniff the mimetype of files. This is used for example to prevent browsers from interpreting text files as JavaScript.
    contentTypeNosniff: true
    #X-Frame-Options,
    #Prevents embedding of the instance within an iframe from other domains to prevent Clickjacking and other similar attacks.#Instructs some browsers to not sniff the mimetype of files. This is used for example to prevent browsers from interpreting text files as JavaScript.
    customFrameOptionsValue: SAMEORIGIN
    #
    referrerPolicy: "no-referrer"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirectregex
  namespace: nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(?:card|cal)dav"
    replacement: "https://$${1}/remote.php/dav"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirectregex2
  namespace: nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "https://([^/]*)(/.well-known[^#]*)"
    replacement: "https://$${1}/index.php$${2}"
