apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 9.4.5
      helm:
        values: |
          env:
            GF_AUTH_ANONYMOUS_ENABLED: true
            GF_SERVER_DOMAIN: graphs.bigli.io
            GF_SERVER_ROOT_URL: https://graphs.bigli.io

          ingress:
            enabled: true
            hosts:
              - graphs.bigli.io
            tls:
              - hosts:
                - graphs.bigli.io
                secretName: graphs-bigli-io-cert
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-desec
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd,kube-system-hsts-headers@kubernetescrd
          persistence:
            enabled: true
            size: 1Gi
            storageClassName: local-path
          rbac:
            namespaced: true
          admin:
            existingSecret: admin-creds
          sidecar:
            datasources:
              initDatasources: true
              enabled: true
    - path: apps/k3s/grafana
      repoURL: https://github.com/TheBigLee/gitops-k3s.git
      targetRevision: HEAD
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
