apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    path: apps/k3s/headscale
    repoURL: https://github.com/TheBigLee/gitops-k3s.git
    targetRevision: HEAD
  destination:
    namespace: headscale
    name: k3s
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
