apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - chart: immich
      repoURL: ghcr.io/immich-app/immich-charts
      targetRevision: 0.9.3
      helm:
        values: |
          image:
            tag: v1.143.1
          envFrom:
            - secretRef:
                name: immich-postgres-user
          env:
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-user
                  key: password
            DB_HOSTNAME: immich-postgres-rw
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-user
                  key: username
            DB_DATABASE_NAME: immich
          immich:
            persistence:
              library:
                existingClaim: immich-data
          redis:
            enabled: true
            architecture: standalone
            auth:
              enabled: false
            master:
              pdb:
                create: false
              persistence:
                annotations:
                  k8up.io/backup: "false"
          server:
            enabled: true
            ingress:
              main:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod-desec
                  traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd,kube-system-hsts-headers@kubernetescrd
                hosts:
                  - host: immich.bigli.io
                    paths:
                      - path: "/"
                  - host: photos.bigli.io
                    paths:
                      - path: "/"
                tls:
                  - hosts:
                    - immich.bigli.io
                    - photos.bigli.io
                    secretName: immich-bigli-io-cert
          machine-learning:
            persistence:
              cache:
                storageClass: local-path
    - path: apps/k3s/immich
      repoURL: https://github.com/TheBigLee/gitops-k3s.git
      targetRevision: HEAD
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
