apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - chart: nextcloud
      repoURL: https://nextcloud.github.io/helm/
      targetRevision: 6.6.9
      helm:
        values: |
          image:
            flavor: fpm
            tag: 30.0.8
          nginx:
            enabled: true
          nextcloud:
            host: nextcloud.bigli.io
            configs:
              bigli-nextcloud.config.php: |
                <?php
                  $CONFIG = [
                    'trusted_proxies' => ['10.43.0.0/16'],
                    'maintenance_window_start' => 1,
                    'csrf.optout' => [
                      '/Nextcloud-android/', // DAVx
                    ],
                    'overwrite.cli.url' => 'https://nextcloud.bigli.io',
                    'overwriteprotocol' => 'https',
                    'overwritehost' => 'nextcloud.bigli.io',
                  ];
            extraEnv:
              - name: "PHP_OPCACHE_MEMORY_CONSUMPTION"
                value: "256"
              - name: "PHP_MEMORY_LIMIT"
                value: "1024M"
            existingSecret:
              enabled: true
              secretName: nextcloud-creds
              usernameKey: username
              passwordKey: password
            extraVolumes:
              - name: cron-config
                configMap:
                  name: cron-config
            extraVolumeMounts:
              - name: cron-config
                mountPath: /var/spool/cron/crontabs/
          resources:
            limits:
              memory: 3Gi
              cpu: 4
            requests:
              memory: 500Mi
              cpu: 500m
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-desec
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd,kube-system-hsts-headers@kubernetescrd,nextcloud-nextcloud-redirectregex@kubernetescrd,nextcloud-nextcloud-headers@kubernetescrd
            tls:
            - secretName: ingress-cert
              hosts:
              - nextcloud.bigli.io
          internalDatabase:
            enabled: false
          postgresql:
            global:
              postgresql:
                auth:
                 existingSecret: psql-creds
                 secretKeys:
                   adminPasswordKey: adminPassword
                   userPasswordKey: db-password
                   replicationPasswordKey: replicationKey
            enabled: true
            primary:
              networkPolicy:
                enabled: false
              podAnnotations:
                k8up.io/backupcommand: '/bin/bash -c "PGPASSWORD=${POSTGRES_PASSWORD} pg_dump -U ${POSTGRES_USER} -Fc ${POSTGRES_DATABASE}"'
              resources:
                limits:
                  memory: 1Gi
              persistence:
                enabled: true
                storageClass: local-path
                annotations:
                  k8up.io/backup: "false"
          redis:
            enabled: true
            networkPolicy:
              enabled: false
            auth:
              existingSecret: redis-creds
              existingSecretPasswordKey: redisPassword
            replica:
              replicaCount: 0
            master:
              persistence:
                annotations:
                  k8up.io/backup: "false"
          cronjob:
            enabled: true
          externalDatabase:
            type: postgresql
            existingSecret:
              enabled: true
              secretName: psql-creds
          persistence:
            enabled: true
          startupProbe:
            enabled: true
          metrics:
            enabled: true
            info:
              apps: true
            serviceMonitor:
              enabled: true
    - path: apps/k3s/nextcloud
      repoURL: https://github.com/TheBigLee/gitops-k3s.git
      targetRevision: HEAD
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
