apiVersion: v1
kind: Secret
metadata:
    name: influx-credentials
type: Opaque
stringData:
    influxdb-password: ENC[AES256_GCM,data:tOF20i4LGa9Jl4YR8OoDtvpRYMKb4O7ul8efc2YrEm4=,iv:nLKNaFJMRtS60oQam8IFcxmt6VPkGUv3a+pjjQm+tRc=,tag:tA2SkxFrqp1rf/W792Q49g==,type:str]
    influxdb-user: ENC[AES256_GCM,data:iuc5ILd/Ub0=,iv:pUegbyYYUuFAEPgTHetwQiWFR1VuuqMKx5EirXEo3qo=,tag:gkdozI378DEtEhO6xVzfQw==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK2Q0bkZxMDlTN3djSmtE
            TDg3RVZsUXhRVGJ4TEtSU2pPbTl2RWU2MnpNCnh0OTNMdFROSmZHOGU3K2RlanVz
            eTZuRzJlRGlzWElwa2Z4bytQR3NTWVUKLS0tIGxPSnpjWVd4ZmNtSVlIaHcxRGtW
            VzdDOC8wWkdFdFBkazkvYUVVZ0gveDAKcQZ0ruKANe0e/An+cKACNxcZdC5kFnMd
            F3eYVwCwXyDgw4n8NIf8uJbj1ksf3ElajzXWwBkLC5phZvnmPSr9iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T10:57:37Z"
    mac: ENC[AES256_GCM,data:TWPIycy9VVMoY+U7oicFyzWKb6UJhwV1VWPjha1H3j3p37KesLz2NnRUSItG7oBHgef7ERdQlmDie+RO5M3eyVLsRHe6Pgq06OG9YpByi6ylNeH+ezP5diECVXiXOygoqQJP0hi4zinAil/eIJ7Jsj7Ew89AUdkLphTXuP2+6mk=,iv:9edNltPsx45sWwxhGhYfLYxf6nLJ6jUYuK3Oseu3fho=,tag:9wn1sIo7FDs/aeITYXChPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
