apiVersion: v1
kind: Secret
metadata:
    name: influx-credentials
type: Opaque
stringData:
    influxdb-password: ENC[AES256_GCM,data:tOF20i4LGa9Jl4YR8OoDtvpRYMKb4O7ul8efc2YrEm4=,iv:nLKNaFJMRtS60oQam8IFcxmt6VPkGUv3a+pjjQm+tRc=,tag:tA2SkxFrqp1rf/W792Q49g==,type:str]
    influxdb-user: ENC[AES256_GCM,data:iuc5ILd/Ub0=,iv:pUegbyYYUuFAEPgTHetwQiWFR1VuuqMKx5EirXEo3qo=,tag:gkdozI378DEtEhO6xVzfQw==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcnVrVmIyM2I0aFd6bVls
            TXhzTDZjWUYxQ3Jnc1gxM1hnTU1zWUJvd0EwCkRCSGpCNFV6aFlwMDBsc3ROTUpL
            ZXV6azBwY3JiaEZ2Rk9hUzF5eWQ0Mm8KLS0tIDR4Z0FCbFBzdHAwTFdEU0FWUFVG
            dUh0R28rb3N6Tnpoc3pKWHIzSVBQY1kKFAjI5W1vdVa3QNjCrTRzBi1DPC8BGQq7
            9M79K5V0L6Wx76WiNwSas4B719ARox0e51DQ41JcDNlCQiZS7qyTmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNGlXWEJ1SnVuNU1BTjcr
            eE9NQjFTYVBJVlNBZXAzTmpCaElaYkQ3T3ljCjlEaEhvRWY0dTV5RzNkTjc0a3ZY
            Q1EyM21DRFplY1doOCtTRVJ4NDJiU1UKLS0tIEt6elRaNW1WZTY0SkRoNzY4QW9Y
            UkhaZGhheWgzT3Y1dE9IamV4TCt0NFEKWI6zoRlKrL1hw/taABsVEKj6ouSMytMC
            Zz63gkD6wCbapRNXWVqj+t6l1MP2SxwH+eNEyggKx5t55b/swFMpEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybWxFQlE2UFFmQnoxdUIr
            RGJ1cEc2UTZXdks5R2NtYWpFYmlpWW8rdnpZCk9hNlF2cEdZdldIdzlxb0V3dEE3
            ZGVQUm4rWWVsdGh6am1yV1VnV0N5MFkKLS0tIHlTNWdRMkcwcmdkN1lIenZINEMr
            R01Zc09jN0lKbFMzaUJsR0pkejJGWGMKtHJolgB0/Y6yV51I+6XMFw70DM6mpkqJ
            GQVMrGc0D9CBbOLliLu78ZcENN2lXR1cFTyx2wBPGajUOLtcXO9rqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T10:57:37Z"
    mac: ENC[AES256_GCM,data:TWPIycy9VVMoY+U7oicFyzWKb6UJhwV1VWPjha1H3j3p37KesLz2NnRUSItG7oBHgef7ERdQlmDie+RO5M3eyVLsRHe6Pgq06OG9YpByi6ylNeH+ezP5diECVXiXOygoqQJP0hi4zinAil/eIJ7Jsj7Ew89AUdkLphTXuP2+6mk=,iv:9edNltPsx45sWwxhGhYfLYxf6nLJ6jUYuK3Oseu3fho=,tag:9wn1sIo7FDs/aeITYXChPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
