apiVersion: v1
kind: Secret
metadata:
    name: backup-bucket-credentials
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:oalOE8ftcN6joA+Gq1uZ3bmcrfN7mdTZWg==,iv:98yBZjlIaSlL8hxlgKZuFozB08+tFZB8VtlOvUCWUss=,tag:bmEw3riX4Gf7KXdsvDzkVA==,type:str]
    access-key-secret: ENC[AES256_GCM,data:M8RoQqkjrICbfqsGqc13pFc6rVoR0ggY6N1aeiBkbQ==,iv:nEiJlkGmNmSGBk3aG9HPlKiZkPAkuOxgdgCiEp28/JI=,tag:kqGT1TcsX1vvCLCTBZq83g==,type:str]
    password: ENC[AES256_GCM,data:7KeBnt4ySaQRnYzh0U9RRwyQGi3WfRybvml44Z+QS3A=,iv:q4i17ddINF8bfQ71bnYKfeLxH80Z25emPI6uawyEfF0=,tag:KHjYYLe/c+DZOIAWgu4PFg==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK2Q0bkZxMDlTN3djSmtE
            TDg3RVZsUXhRVGJ4TEtSU2pPbTl2RWU2MnpNCnh0OTNMdFROSmZHOGU3K2RlanVz
            eTZuRzJlRGlzWElwa2Z4bytQR3NTWVUKLS0tIGxPSnpjWVd4ZmNtSVlIaHcxRGtW
            VzdDOC8wWkdFdFBkazkvYUVVZ0gveDAKcQZ0ruKANe0e/An+cKACNxcZdC5kFnMd
            F3eYVwCwXyDgw4n8NIf8uJbj1ksf3ElajzXWwBkLC5phZvnmPSr9iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-08T07:50:43Z"
    mac: ENC[AES256_GCM,data:eP1lWpDar0FpHbzyiZxVHjOHzCO0xGyxgGnjmtOvr9rgtY6OI0XOXVId93zY+uye1ZV/A1NtZ6cBvtqytz5SLf8GET6/5HpopuBrJBvYb6M8mWr3pTNqvPKKIe+urnblQiEG9fnl9rn9i+MN1dlV4Ca73wPQzgzqrYVyttiNnUE=,iv:lL7VmY77IbT4srCna+/pm11VVR9OQp/9TmYTuFWDMtA=,tag:XMLMXjKHRzPiWHelphjy6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
