apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-user
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:o4qL7oTK,iv:20T2R4CXtk37aG2nsWIwiREHLPi7KijjXe2MUZnMOhE=,tag:GKQgYomIegmVzaX9MT4PXg==,type:str]
    password: ENC[AES256_GCM,data:NCf+53FbpP24Q/JTelsvRzexdMs2fnL3auiI42UEDzs=,iv:zQ3B7N/9/mV14KBRxIb0iJzt0yOZHKY0V1w5NbcF6yk=,tag:C+qrnqYUK2QHPKbin97HGQ==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibzlDRC9EdUhtZWVETlNX
            bGRXY01hbVJCMUNjMzFlYW1CcGZBM2lMK204CkNPVkNJeVh6N2U5TG9FV1lTa0pk
            clZESHljTlgvU0w3YmZGQzU0cnViWXMKLS0tIHhTUGNuRFNzUWxYaFVrNGJ6SUdl
            L0NmeGkwZmM4eXNTbVc3dDFNRjJNVEkKFhr7cEab4M2qJxo+BOQVTiGQ/ociDvQu
            ls344ti8f1ZdUC0U6FeRuedjYPFOPF0sbFt6IR1PJSC5SSLyKSZ4sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bWlnN0JzKytsVEI2ZnBw
            blI5STJZem1NQTBSNmFUTWtCOVlBaVJBOGc0CnZ1bDdjTy8yUXZQUnAvVUpUYWVj
            by9BK3hRMVVkSytpRkZJeVJ2Wmd0MUUKLS0tIG1JUmtWakV0WFpscFcvOG03U25k
            bE1FZTRSYzhuU1ArdHdHME9Pc0hLVFkKKk8WutiAXljnjbaLBuSVFcDwX0OvTt77
            8Dgy4AMwLJ/wC3ElzmVQ3SQmIvaiYyxIsox0ouAh3z8TkJEr1wAxsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCckVqdU1lTkFoNTdraFQz
            M2xlcEtaczA5UDRzcHdSTDdxeHp3Zms4MFJzCnZkWnFLeHg4R2NaR2Q0dGxlZC95
            alZZVUpVamhLajZqSWJ3ZTZUblNOejgKLS0tIGN4TldkT0kzRVY2dTZZc2hFY243
            WmlMc0RJYU9NQS9Xd2RMWDJiSVpaQVEKIvXXfjrfG/pMEUCd6wKSnKn1xntv2id/
            BeKoIO8ODS3wosv09DS6EM9+gZD7pthyewywCB3TDmH6FvxMoaMQRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T20:51:16Z"
    mac: ENC[AES256_GCM,data:5kkxiIi+O48pX8Ac6OOO7CVdtV0ih5e703cVL/nO5CQUGo6jkBfQfyGR9c22K8JbC0GQAMtmXEoVSg2vQDNYc6yOpow8Mr+q3gdP+52J+yOm0pKdjvwJCqykv+ygN3UNIJP6BH165YSJMYbGEJypkzRsvBhSxJulrkYhC6jbtyc=,iv:+/cXfmLeTZM4Ja1ZmQlbJBMkeaqouskre1x1uGOCdtQ=,tag:Fo+4K3S0u/TcBqTvOF2r6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
