apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-user
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:o4qL7oTK,iv:20T2R4CXtk37aG2nsWIwiREHLPi7KijjXe2MUZnMOhE=,tag:GKQgYomIegmVzaX9MT4PXg==,type:str]
    password: ENC[AES256_GCM,data:NCf+53FbpP24Q/JTelsvRzexdMs2fnL3auiI42UEDzs=,iv:zQ3B7N/9/mV14KBRxIb0iJzt0yOZHKY0V1w5NbcF6yk=,tag:C+qrnqYUK2QHPKbin97HGQ==,type:str]
sops:
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK2Q0bkZxMDlTN3djSmtE
            TDg3RVZsUXhRVGJ4TEtSU2pPbTl2RWU2MnpNCnh0OTNMdFROSmZHOGU3K2RlanVz
            eTZuRzJlRGlzWElwa2Z4bytQR3NTWVUKLS0tIGxPSnpjWVd4ZmNtSVlIaHcxRGtW
            VzdDOC8wWkdFdFBkazkvYUVVZ0gveDAKcQZ0ruKANe0e/An+cKACNxcZdC5kFnMd
            F3eYVwCwXyDgw4n8NIf8uJbj1ksf3ElajzXWwBkLC5phZvnmPSr9iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T20:51:16Z"
    mac: ENC[AES256_GCM,data:5kkxiIi+O48pX8Ac6OOO7CVdtV0ih5e703cVL/nO5CQUGo6jkBfQfyGR9c22K8JbC0GQAMtmXEoVSg2vQDNYc6yOpow8Mr+q3gdP+52J+yOm0pKdjvwJCqykv+ygN3UNIJP6BH165YSJMYbGEJypkzRsvBhSxJulrkYhC6jbtyc=,iv:+/cXfmLeTZM4Ja1ZmQlbJBMkeaqouskre1x1uGOCdtQ=,tag:Fo+4K3S0u/TcBqTvOF2r6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
