apiVersion: v1
kind: Secret
metadata:
    name: psql-creds
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:PizXl74N2w9/rdqSfpLyz6EuhuGu9Pag4ensuQqkNmU=,iv:cKKZj3Hg4ToLLRBDzSr/iKilrk8sSv14AhyHW1Gt7Bk=,tag:ddPGh8zI8XSDyfUiLIRQrQ==,type:str]
    db-username: ENC[AES256_GCM,data:QzlrTu7X/8u/,iv:MQaiwCbhOzxOJBBHXNSboEQtNgnzCLTrP9G4v5u+n8M=,tag:x0rMnWYGojzGA6S3reYJ9w==,type:str]
    db-password: ENC[AES256_GCM,data:XWSuPSTyZbxfRSufMTPxysdP4uUh8vB3uqoSshtD/XI=,iv:Q9MeTzQBESHQmgPhBPd0yQAuERIxsdQHHfWU9PfW4Ko=,tag:dRJdkltqdRsI7o9uAJuFKg==,type:str]
    replicationKey: ENC[AES256_GCM,data:6FidX6vHBVYCaFsCPzVWydsACgiTAsCCnXZT445zqio=,iv:SUVkufza34hPGqoyIe9bFeDXt6LB4guKSZcwUsPFQnA=,tag:ySkARQT9EbO2qdDOzaQEMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENmw2djlwRVFJSnlMUGVF
            K0xsVkRUd0h6QXN6ZVY1VTVwNW1LMTh3N1VBCjY5MGI4Nk5oWG0raGJFM2ROay93
            YXk4VE9WS2dSeTZpRHRYQ0RBVTlDWFEKLS0tIFpRM1pyNWV4dnJDVDFEY1U3Vkhy
            aHpIVmZ0TngrNVRDTStvRnNhUjZPSkUK8Ku6zvTb72AU98k4qoXh+uVcvyYGddbI
            GYJIyHwWaEUCjTkYjS4vO/IsXpCZmB5YFXwTiL7a+ubIKiM3m0lbAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-02T08:36:57Z"
    mac: ENC[AES256_GCM,data:mHdhOyCLTcgGHqRW5rqjQZAMjZMSgexhxiYap0BfWqB+T/ROfOR3oYnQbPzw7Bl0uSjfoFT2lprDlbzAacCLkK1ITssqiWbUkoRCOmvRNrV5l3bwIEEZDDCYOOjgon+zjQcOTNPDQ21cofaBfUvF1F2t9wFeIaSWcj8+GPJgmXk=,iv:Cs0yjzdqknby/AChjJIhpd29DexjxjikJrHfeciwQck=,tag:LQ+LMeidUpYCfsmNjHVUww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
