apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  source:
    path: apps/talos/_system/gateway-api
    repoURL: https://github.com/TheBigLee/gitops-k3s.git
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
