apiVersion: v1
kind: Secret
metadata:
    name: global-s3-credentials
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:9vhILEHcN7vGVzHXx89TQx3uNMMjH3PHtg==,iv:Jqfxg4HBKbaMsN5dkFWxllXpurzfywvcNdcXdC1Z7Bg=,tag:a9lOrFt8NUeMBn6UISQncA==,type:str]
    access-key-secret: ENC[AES256_GCM,data:mdqWtYuA/x6jO5Ss87Mb5Yj3YU2ULogD4K4IO81KHA==,iv:8wT4P6ccQublunBSld87Cg3RFbumCiLt5heclYdXC6M=,tag:PzOQzN9sEOQFdM2FWAa0jA==,type:str]
    endpoint: ENC[AES256_GCM,data:VNKqkTRTM9arxO48G3OJKWhC+ScosUaKXxyxR2sPAJgb,iv:0dpxAO09JOk70oQoFZWvOZN6lVfPvRjjsKrRClWOdHY=,tag:lvDHCUsr+X2egXgU/l2Rjg==,type:str]
    bucket: ENC[AES256_GCM,data:5HP3otXeCv+2CVrlwi/EqUSmXw==,iv:0H1NBuo1Ej036M/StbdcuUJraCg13F9UNTh3lXJ99YY=,tag:O6IIKh1/LsaxF8YVfYTAVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjrv5skm6p380h8smk4x9sp2m0valkz7ldh4npqrrk55vrwn0veqsvv375
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK2Q0bkZxMDlTN3djSmtE
            TDg3RVZsUXhRVGJ4TEtSU2pPbTl2RWU2MnpNCnh0OTNMdFROSmZHOGU3K2RlanVz
            eTZuRzJlRGlzWElwa2Z4bytQR3NTWVUKLS0tIGxPSnpjWVd4ZmNtSVlIaHcxRGtW
            VzdDOC8wWkdFdFBkazkvYUVVZ0gveDAKcQZ0ruKANe0e/An+cKACNxcZdC5kFnMd
            F3eYVwCwXyDgw4n8NIf8uJbj1ksf3ElajzXWwBkLC5phZvnmPSr9iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-01T18:47:33Z"
    mac: ENC[AES256_GCM,data:8a99wW2npyTC6e0sz017ahy0xdRknLzZblsfqo4In2sbc9cEig7jRQF7zRVfisGC1HGmqkQF1uyTWfZxI0MMVAtf7bXmBKya9G0yOdHVktAep9S88fZNH8LU8MSX+mCX9pA9eapklDOeFvFhFqdvX1Qdvc6luR0ugpopriDuAj0=,iv:rCoZhZzcCJ9yovlXNPVvyTXEOtxf/WZoDA/fvrC5NO4=,tag:EFs+OKO2A8rCuIckJPb2OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
