apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kured
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-kured'
    spec:
      project: system
      source:
        chart: kured
        repoURL: https://kubereboot.github.io/charts
        targetRevision: 5.10.0
      destination:
        server: '{{server}}'
        namespace: kured
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
